Mals 130 validate sleepuntil twi match
cgjeffries/DxCore pull request #40
Opened 2023-01-30 09:05 UTC by cgjeffries

### Linked Jira Issue:
https://ser401-2022-group39.atlassian.net/browse/MALS-130

### Description of Changes:
Validated the testing program for waking on twi match, and added a readme with instructions, as well as example current draw measurements.

2023-01-30 20:13 UTC, jnbrauer requested changes

2023-01-30 20:13 UTC, jnbrauer commented on megaavr/extras/testCases/sleepUntilTWIMatch_testCase/README.md
> +14. Observe using the ammeter and the Curiosity nano board's serial output that it no longer wakes from sleep, as teh address is not correct. If the ammeter is sufficiently fast reacting, you may see
```suggestion
14. Observe using the ammeter and the Curiosity nano board's serial output that it no longer wakes from sleep, as the address is not correct. If the ammeter is sufficiently fast reacting, you may see small power spikes as the system received the invalid address. 
```

2023-01-30 20:13 UTC, jnbrauer commented on megaavr/extras/testCases/sleepUntilTWIMatch_testCase/README.md
> +1. Connect the I2C connections of the Curiosity nano board and an Arduino uno compatible board, such as an arduino nano, arduino uno, or atmega328p Xplained mini. No external pull-up resistors are re
```suggestion
1. Connect the I2C connections of the Curiosity Nano board and an Arduino Uno compatible board, such as an Arduino Nano, Arduino Uno, or ATmega328p XPlained Mini. No external pull-up resistors are required. Ensure that the ground pins of each board are connected,
```

2023-01-30 20:13 UTC, jnbrauer commented on megaavr/extras/testCases/sleepUntilTWIMatch_testCase/README.md
> +2. Connect the Curiosity nano board to your computer
```suggestion
2. Connect the Curiosity Nano board to your computer
```

2023-01-30 20:13 UTC, jnbrauer commented on megaavr/extras/testCases/sleepUntilTWIMatch_testCase/README.md
> +3. Connect the curiosity nano power supply in series with an ammeter such as a multimeter or AVR power debugger (recommended)
```suggestion
3. Connect the Curiosity Nano power supply in series with an ammeter such as a multimeter or AVR power debugger (recommended)
```

2023-01-30 20:13 UTC, jnbrauer commented on megaavr/extras/testCases/sleepUntilTWIMatch_testCase/README.md
> +4. Download the "slave" sketch to the Curiosity nano board.
```suggestion
4. Download the "slave" sketch to the Curiosity Nano board.
```

2023-01-30 20:13 UTC, jnbrauer commented on megaavr/extras/testCases/sleepUntilTWIMatch_testCase/README.md
> +5. Connect the Arduino uno compatible board to your computer
```suggestion
5. Connect the Arduino Uno compatible board to your computer
```

2023-01-30 20:13 UTC, jnbrauer commented on megaavr/extras/testCases/sleepUntilTWIMatch_testCase/README.md
> +6. Download the "master" sketch to the uno compatible board.
```suggestion
6. Download the "master" sketch to the Uno compatible board.
```

2023-01-30 20:13 UTC, jnbrauer commented on megaavr/extras/testCases/sleepUntilTWIMatch_testCase/README.md
> +7. Open a serial console in the COM port that the Curiosity nano is on, either using the built-in serial console in the Arduino IDE or using a separate program like PuTTY. Set the Baud rate to **1152
```suggestion
7. Open a serial console in the COM port that the Curiosity Nano is on, either using the built-in serial console in the Arduino IDE or using a separate program like PuTTY. Set the Baud rate to **115200**.
```

2023-01-30 20:13 UTC, jnbrauer commented on megaavr/extras/testCases/sleepUntilTWIMatch_testCase/README.md
> +8. Observe that the curiosity nano sends messages when entering various sleep modes, as well as when the system receives a valid address over TWI.
```suggestion
8. Observe that the Curiosity Nano sends messages when entering various sleep modes, as well as when the system receives a valid address over TWI.
```

2023-01-30 20:13 UTC, jnbrauer commented on megaavr/extras/testCases/sleepUntilTWIMatch_testCase/README.md
> +9. Open a serial console in the COM port that the Arduino uno compatible board is on. Set the Baud rate to **57600**.
```suggestion
9. Open a serial console in the COM port that the Arduino Uno compatible board is on. Set the Baud rate to **57600**.
```

2023-01-30 20:13 UTC, jnbrauer commented on megaavr/extras/testCases/sleepUntilTWIMatch_testCase/README.md
> +12. Revise the `twiAddress` in the Master sketch to a valid value other than 0x08, such as 0x0A.
```suggestion
12. Revise the `twiAddress` in the master sketch to a valid value other than 0x08, such as 0x0A.
```

2023-01-31 01:53 UTC, cgjeffries commented
@jnbrauer committed your suggestions, thank you.

2023-01-31 01:55 UTC, jnbrauer approved these changes
Looks good!

2023-01-31 01:55 UTC, merged