Mals 189 low power functions doc
cgjeffries/DxCore pull request #46
Opened 2023-03-22 22:05 UTC by amtrang

### Linked Jira Issue:
https://ser401-2022-group39.atlassian.net/jira/software/projects/MALS/issues/MALS-189

### Description of Changes:
Create a document describing the new low-power mode functionality.

### Acceptance Criteria:
- [x] AC1: A single document describing all added low-power mode features has been created
- [x] AC2: Document has been placed in the DxCore repository

2023-03-22 23:34 UTC, jnbrauer requested changes

2023-03-22 23:34 UTC, jnbrauer commented on megaavr/extras/LowPower.md
> +    All information for the hardware changes and interrupts can be found in the AVR128DA48 datasheet from Microchip which can be found here: https://www.microchip.com/en-us/product/AVR128DA48
Not quite sure why but GitHub is rendering all of the indented sections as code blocks, let's fix that so these sections display as paragraphs. 
```suggestion
This document is a comprehensive list of all the functions from LowPower.cpp. Each function includes descriptions for how they change the hardware to decrease the power draw for DxCore microcontrollers.
All information for the hardware changes and interrupts can be found in the AVR128DA48 datasheet from Microchip which can be found here: https://www.microchip.com/en-us/product/AVR128DA48
```

2023-03-22 23:34 UTC, jnbrauer commented on megaavr/extras/LowPower.md
> +Description:
These labels could be either level 3 headers or bolded to make them more distinct.

2023-03-22 23:34 UTC, jnbrauer commented on megaavr/extras/LowPower.md
> +# LowPower.cpp
Let's add a paragraph or two at the start of this document describing the features of the low-power library and its goals at a high level.

2023-03-22 23:34 UTC, jnbrauer commented on megaavr/extras/LowPower.md
> +    sleepMode - the type of sleep mode the microcontroller will use when it enters sleep mode.
I would suggest using code tags for function arguments, names, and sample calls throughout. 

```suggestion
`sleepMode` - the type of sleep mode the microcontroller will use when it enters sleep mode.
```

2023-03-23 04:28 UTC, cgjeffries requested changes
Content looks fine at a glance, but I think formatting could be improved.
Perhaps we could re-use/repurpose the content from the API design doc we created in the beginning? https://github.com/jnbrauer/SER401-2022-Group39-Documentation/blob/main/low_power_api_design.md

2023-03-26 04:09 UTC, jnbrauer approved these changes

2023-03-26 04:45 UTC, merged