Documentation added for extended ADC config functionality
cgjeffries/DxCore pull request #47
Opened 2023-03-24 19:54 UTC by mpcender

### Linked Jira Issue:
https://ser401-2022-group39.atlassian.net/browse/MALS-190

### Description of Changes:
Added document describing the functionality added to the DxCore for ADC.

### Acceptance Criteria:
- [x] AC1: A single document describing all added ADC features has been created
- [x] AC2: Document has been placed in the DxCore repository

2023-03-25 22:53 UTC, jnbrauer requested changes

2023-03-25 22:53 UTC, jnbrauer commented on megaavr/extras/Ref_ADC_config.md
> +analogReadSampleNum(), and analogReadPrescaler() are introduced for reading and
Let's put these function names, and the struct name above, in code tags.

2023-03-25 22:53 UTC, jnbrauer commented on megaavr/extras/Ref_ADC_config.md
> +	uint8_t sampleLen;   // ADC sampling time in ADC clock cycles
```suggestion
    uint8_t muxNeg;      // Negative pin for differential ADC conversion
    uint8_t resolution;  // ADC bit resolution
    uint8_t prescaler;   // ADC clock prescaler value
    uint8_t sampleNum;   // Number of ADC samples to accumulate
    uint8_t sampleDelay; // Delay between ADC samples in accumulation mode
    uint8_t sampleLen;   // ADC sampling time in ADC clock cycles
```

2023-03-25 22:53 UTC, jnbrauer commented on megaavr/extras/Ref_ADC_config.md
> +- 0x7: 128 samples (`ADC_SAMPNUM_ACC128_gc`)
I believe this is incorrect, as this is implemented now you pass in the actual desired number of samples. Also, let's avoid referencing the internal constants (`ADC_SAMPNUM_NONE_gc` etc.), most users probably won't know where those are coming from.

2023-03-25 22:53 UTC, jnbrauer commented on megaavr/extras/Ref_ADC_config.md
> +- 0xD: clock divided by 256 (`ADC_PRESC_DIV256_gc`)
Same comments as above.

2023-03-27 16:47 UTC, mpcender commented
Thanks for the notes! Good eye on the function input params. I hadn't realized those had changed from the original API design. Should all be updated

2023-03-27 17:19 UTC, jnbrauer approved these changes
Looks good!

2023-03-27 18:28 UTC, closed without merging